### ISSUE TITLE
Content Management Tools - edits required

### ISSUE THREAD

**Issue by Laura-Novich-OBW** [Laura-Novich-OBW/Tool-Chest#65]
@Schnee18 @ShlomoRBarron @AlanFFM 
In the readme file: 
As such, these systems often include tools found in other categories covered by this review project.

I would change review to research. Alternatively you can use GitHub, OBW, or just remove it all together. For example:  ~~review~~ project. 

For all "tool pages" - please add a short description between the title and the table. Short descriptions are mandatory for all topic pages. They are used to help Google Search and provide a break between the table and the heading. 

# Wix

- Tested templates Various tried and tested templates for ~~various~~ (choose another word) industries are available for free or for purchase.
- Performance
Compared to other content management tools, Wix might not be as performant, especially when mulriple plugins are being used. (please fix spelling)

# Drupal
- Knowledge apriori
Requires technical expertise for complex setups. (please fix spelling)

# Paligo
- Paligo is a cloud-based component content management system based on DocBook, with a user-friendly interface. 
**comment** - DocBook is a form of XML but the problem is most people don't know that. Please add XML to DocBook. For example DocBook XML. 

- Dependence on the internet
Limits work to when internet access is available, and can affect performance.
Change title. It's not the internet. Your dependence is to be online and you're also dependent on their servers. So the key is that offline editing is not supported and it is not suitable for air-gapped systems. 

# Ixia
Feature-filled
A feature rich authoring environment with capabilities for tagging, content reuse, and cross-referencing. Please change ~~feature rich~~ to feature-rich. 

# Heretto 
This comment is true for all cloud based SAAS solutions - the software must be used online which means it is not applicable to air-gapped systems. While this may not be a disadvantage to all, it is for some.

**Comment by ShlomoRBarron** [comment]
Readme file edited as well as WordPress and Heretto.

**Comment by ShlomoRBarron** [comment]
All done?

**Comment by Laura-Novich-OBW** [comment]
nicely done!
